name: tar-project
channels:
# order matters, channels are tried sequentially starting from the first one
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - huggingface
dependencies:
  - python=3.9
  - numpy=1.22.3
  - matplotlib=3.5.2
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.11.0
  - scikit-learn=1.1.0
  - pandas=1.4.2
  - transformers=4.19.2
  - pytorch::torchtext=0.12.0
  - spacy=3.3
# uncomment the stuff below when first pip package is needed
#  - pip=21.2.4
#  - pip:
#     - list_pip_packages_here
