name: tar-project
channels:
# order matters, channels are tried sequentially starting from the first one
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - huggingface
dependencies:
  - python=3.9
  - numpy=1.22.3
  - matplotlib=3.5.2
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.11.0
  - scikit-learn=1.1.0
  - pandas=1.4.2
  - spacy=3.3
  - pip=21.2.4
  - pip:
    - adapter-transformers==3.0.1
    - wandb==0.12.17
    - datasets==2.2.1
