name: "adapter-bottleneck"
description: "Adapter fine-tuning using the Pfeiffer bottleneck configuration."
paper: "https://arxiv.org/abs/2005.00247"
data:
  data_dir: "data"
  train_file: "train.txt"
  dev_file: "dev.txt"
  test_file: "test.txt"
model:  # model-specific configuration
  type: adapter  # type of the model to use. Currently supported: ["adapter", "bitfit"]
  adapter_config: pfeiffer  # adapter config, used only if the model type is "adapter".
training_args:  # training arguments passed to the trainer
  learning_rate: 0.0001
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0
  num_train_epochs: 30
  adapter: True
  adapter_config: pfeiffer
