name: "adapter-test"
description: "Test for the adapter fine-tuning configuration."
# data is redundant, present in every file. move to data.yaml
data:
  data_dir: "data"
  train_file: "train.txt"
  dev_file: "dev.txt"
  test_file: "test.txt"
model:
  type: adapter
  adapter_config: pfeiffer
training_args:
  learning_rate: 0.0001
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0.01
  num_train_epochs: 1
