name: "bitfit"
description: "Fine-tuning only biases and the classification head."
paper: "https://arxiv.org/pdf/2106.10199.pdf"
data:
  data_dir: "data"
  train_file: "train.txt"
  dev_file: "dev.txt"
  test_file: "test.txt"
model:  # model-specific configuration
  type: bitfit  # type of the model to use. Currently supported: ["adapter", "bitfit"]
training_args:  # training arguments passed to the trainer
  learning_rate: 0.0001
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0
  num_train_epochs: 20
  warmup_percentage: 0.10
